version: "3.9"
services:
  mongodb:
    image: 'mongo:5.0.6'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - .docker/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - .docker/mongo/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root-db
